export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const CHANGE_USER = "CHANGE_USER";
export const CHANGE_NOTIFICATION = "CHANGE_NOTIFICATION";
